services:
    Wallabag\UserBundle\Mailer\AuthCodeMailer:
        class: Wallabag\UserBundle\Mailer\AuthCodeMailer
        arguments:
            - "@mailer"
            - "@twig"
            - "%scheb_two_factor.email.sender_email%"
            - "%scheb_two_factor.email.sender_name%"
            - '@=service(''craue_config'').get(''wallabag_support_url'')'
            - '%domain_name%'

    Wallabag\UserBundle\EventListener\RegistrationListener:
        arguments:
            - '%fosuser_registration%'
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    Wallabag\UserBundle\EventListener\PasswordResettingListener:
        class: Wallabag\UserBundle\EventListener\PasswordResettingListener
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    Wallabag\UserBundle\Repository\UserRepository:
        class: Wallabag\UserBundle\Repository\UserRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - WallabagUserBundle:User

    Wallabag\UserBundle\EventListener\CreateConfigListener:
        class: Wallabag\UserBundle\EventListener\CreateConfigListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%wallabag_core.theme%"
            - "%wallabag_core.items_on_page%"
            - "%wallabag_core.feed_limit%"
            - "%wallabag_core.language%"
            - "%wallabag_core.reading_speed%"
            - "%wallabag_core.action_mark_as_read%"
            - "%wallabag_core.list_mode%"
            - "@session"
        tags:
            - { name: kernel.event_subscriber }

    Wallabag\UserBundle\EventListener\AuthenticationFailureListener:
        class: Wallabag\UserBundle\EventListener\AuthenticationFailureListener
        arguments:
            - "@request_stack"
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }
