version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: stylelint
    versions:
    - "> 7.13.0"
  - dependency-name: stylelint-config-standard
    versions:
    - "> 16.0.0"
  - dependency-name: stylelint-webpack-plugin
    versions:
    - ">= 2.a"
    - "< 3"
  - dependency-name: webpack-cli
    versions:
    - ">= 4.a"
    - "< 5"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - j0k3r
  - tcitworld
  - Kdecherf
  labels:
  - Ready for review
  ignore:
  - dependency-name: doctrine/doctrine-migrations-bundle
    versions:
    - "> 1.3.2"
  - dependency-name: friendsofsymfony/user-bundle
    versions:
    - "> 2.0.2"
  - dependency-name: nelmio/api-doc-bundle
    versions:
    - "> 2.13.4"
  - dependency-name: symfony/phpunit-bridge
    versions:
    - ">= 4.4.a"
    - "< 4.5"
  - dependency-name: symfony/phpunit-bridge
    versions:
    - ">= 5.0.a"
    - "< 5.1"
