imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }
    - { resource: services_test.yml }

parameters:
    fosuser_registration: true

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    translator:
        enabled: false
    mailer:
        dsn: 'null://null'

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        dbname_suffix: '_test' # for MySQL and PostgreSQL

    orm:
        metadata_cache_driver:
            type: service
            id: filesystem_cache
        query_cache_driver:
            type: service
            id: filesystem_cache
