services:
    filesystem_cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments:
            - "%kernel.cache_dir%/doctrine/metadata"

    # fixtures
    Wallabag\DataFixtures\:
        resource: '../../src/DataFixtures/*'
        tags: ['doctrine.fixture.orm']
        autowire: true
