# RabbitMQ stuff
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    wallabag_import.consumer.amqp.pocket:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\PocketImport'

    wallabag_import.consumer.amqp.readability:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\ReadabilityImport'

    wallabag_import.consumer.amqp.instapaper:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\InstapaperImport'

    wallabag_import.consumer.amqp.pinboard:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\PinboardImport'

    wallabag_import.consumer.amqp.delicious:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\DeliciousImport'

    wallabag_import.consumer.amqp.wallabag_v1:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\WallabagV1Import'

    wallabag_import.consumer.amqp.wallabag_v2:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\WallabagV2Import'

    wallabag_import.consumer.amqp.elcurator:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\ElcuratorImport'

    wallabag_import.consumer.amqp.firefox:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\FirefoxImport'

    wallabag_import.consumer.amqp.chrome:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\ChromeImport'
