# RabbitMQ stuff
services:
    wallabag_import.consumer.amqp.pocket:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\PocketImport'
            - "@event_dispatcher"
            - "@logger"
    wallabag_import.consumer.amqp.readability:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\ReadabilityImport'
            - "@event_dispatcher"
            - "@logger"
    wallabag_import.consumer.amqp.instapaper:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\InstapaperImport'
            - "@event_dispatcher"
            - "@logger"
    wallabag_import.consumer.amqp.pinboard:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\PinboardImport'
            - "@event_dispatcher"
            - "@logger"
    wallabag_import.consumer.amqp.delicious:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\DeliciousImport'
            - "@event_dispatcher"
            - "@logger"
    wallabag_import.consumer.amqp.wallabag_v1:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\WallabagV1Import'
            - "@event_dispatcher"
            - "@logger"
    wallabag_import.consumer.amqp.wallabag_v2:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\WallabagV2Import'
            - "@event_dispatcher"
            - "@logger"
    wallabag_import.consumer.amqp.elcurator:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\ElcuratorImport'
            - "@event_dispatcher"
            - "@logger"
    wallabag_import.consumer.amqp.firefox:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\FirefoxImport'
            - "@event_dispatcher"
            - "@logger"
    wallabag_import.consumer.amqp.chrome:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\ChromeImport'
            - "@event_dispatcher"
            - "@logger"
