# Redis stuff
services:
    # readability
    wallabag_import.queue.redis.readability:
        class: Simpleue\Queue\RedisQueue
        arguments:
            - '@Predis\Client'
            - "wallabag.import.readability"

    wallabag_import.producer.redis.readability:
        class: Wallabag\ImportBundle\Redis\Producer
        arguments:
            - "@wallabag_import.queue.redis.readability"

    wallabag_import.consumer.redis.readability:
        class: Wallabag\ImportBundle\Consumer\RedisEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\ReadabilityImport'
            - "@event_dispatcher"
            - "@logger"

    # instapaper
    wallabag_import.queue.redis.instapaper:
        class: Simpleue\Queue\RedisQueue
        arguments:
            - '@Predis\Client'
            - "wallabag.import.instapaper"

    wallabag_import.producer.redis.instapaper:
        class: Wallabag\ImportBundle\Redis\Producer
        arguments:
            - "@wallabag_import.queue.redis.instapaper"

    wallabag_import.consumer.redis.instapaper:
        class: Wallabag\ImportBundle\Consumer\RedisEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\InstapaperImport'
            - "@event_dispatcher"
            - "@logger"

    # pinboard
    wallabag_import.queue.redis.pinboard:
        class: Simpleue\Queue\RedisQueue
        arguments:
            - '@Predis\Client'
            - "wallabag.import.pinboard"

    wallabag_import.producer.redis.pinboard:
        class: Wallabag\ImportBundle\Redis\Producer
        arguments:
            - "@wallabag_import.queue.redis.pinboard"

    wallabag_import.consumer.redis.pinboard:
        class: Wallabag\ImportBundle\Consumer\RedisEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\PinboardImport'
            - "@event_dispatcher"
            - "@logger"

    # delicious
    wallabag_import.queue.redis.delicious:
        class: Simpleue\Queue\RedisQueue
        arguments:
            - '@Predis\Client'
            - "wallabag.import.delicious"

    wallabag_import.producer.redis.delicious:
        class: Wallabag\ImportBundle\Redis\Producer
        arguments:
            - "@wallabag_import.queue.redis.delicious"

    wallabag_import.consumer.redis.delicious:
        class: Wallabag\ImportBundle\Consumer\RedisEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\DeliciousImport'
            - "@event_dispatcher"
            - "@logger"

    # pocket
    wallabag_import.queue.redis.pocket:
        class: Simpleue\Queue\RedisQueue
        arguments:
            - '@Predis\Client'
            - "wallabag.import.pocket"

    wallabag_import.producer.redis.pocket:
        class: Wallabag\ImportBundle\Redis\Producer
        arguments:
            - "@wallabag_import.queue.redis.pocket"

    wallabag_import.consumer.redis.pocket:
        class: Wallabag\ImportBundle\Consumer\RedisEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\PocketImport'
            - "@event_dispatcher"
            - "@logger"

    # wallabag v1
    wallabag_import.queue.redis.wallabag_v1:
        class: Simpleue\Queue\RedisQueue
        arguments:
            - '@Predis\Client'
            - "wallabag.import.wallabag_v1"

    wallabag_import.producer.redis.wallabag_v1:
        class: Wallabag\ImportBundle\Redis\Producer
        arguments:
            - "@wallabag_import.queue.redis.wallabag_v1"

    wallabag_import.consumer.redis.wallabag_v1:
        class: Wallabag\ImportBundle\Consumer\RedisEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\WallabagV1Import'
            - "@event_dispatcher"
            - "@logger"

    # wallabag v2
    wallabag_import.queue.redis.wallabag_v2:
        class: Simpleue\Queue\RedisQueue
        arguments:
            - '@Predis\Client'
            - "wallabag.import.wallabag_v2"

    wallabag_import.producer.redis.wallabag_v2:
        class: Wallabag\ImportBundle\Redis\Producer
        arguments:
            - "@wallabag_import.queue.redis.wallabag_v2"

    wallabag_import.consumer.redis.wallabag_v2:
        class: Wallabag\ImportBundle\Consumer\RedisEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\WallabagV2Import'
            - "@event_dispatcher"
            - "@logger"

    # elcurator
    wallabag_import.queue.redis.elcurator:
        class: Simpleue\Queue\RedisQueue
        arguments:
            - '@Predis\Client'
            - "wallabag.import.elcurator"

    wallabag_import.producer.redis.elcurator:
        class: Wallabag\ImportBundle\Redis\Producer
        arguments:
            - "@wallabag_import.queue.redis.elcurator"

    wallabag_import.consumer.redis.elcurator:
        class: Wallabag\ImportBundle\Consumer\RedisEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\ElcuratorImport'
            - "@event_dispatcher"
            - "@logger"

    # firefox
    wallabag_import.queue.redis.firefox:
        class: Simpleue\Queue\RedisQueue
        arguments:
            - '@Predis\Client'
            - "wallabag.import.firefox"

    wallabag_import.producer.redis.firefox:
        class: Wallabag\ImportBundle\Redis\Producer
        arguments:
            - "@wallabag_import.queue.redis.firefox"

    wallabag_import.consumer.redis.firefox:
        class: Wallabag\ImportBundle\Consumer\RedisEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\FirefoxImport'
            - "@event_dispatcher"
            - "@logger"

    # chrome
    wallabag_import.queue.redis.chrome:
        class: Simpleue\Queue\RedisQueue
        arguments:
            - '@Predis\Client'
            - "wallabag.import.chrome"

    wallabag_import.producer.redis.chrome:
        class: Wallabag\ImportBundle\Redis\Producer
        arguments:
            - "@wallabag_import.queue.redis.chrome"

    wallabag_import.consumer.redis.chrome:
        class: Wallabag\ImportBundle\Consumer\RedisEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\UserBundle\Repository\UserRepository'
            - '@Wallabag\ImportBundle\Import\ChromeImport'
            - "@event_dispatcher"
            - "@logger"
