imports:
    - { resource: rabbit.yml }
    - { resource: redis.yml }

services:
    Wallabag\ImportBundle\Import\ImportChain:
        class: Wallabag\ImportBundle\Import\ImportChain

    wallabag_import.pocket.client:
        alias: 'httplug.client.wallabag_import.pocket.client'

    Wallabag\ImportBundle\Import\PocketImport:
        class: Wallabag\ImportBundle\Import\PocketImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\CoreBundle\Helper\ContentProxy'
            - '@Wallabag\CoreBundle\Helper\TagsAssigner'
            - "@event_dispatcher"
        calls:
            - [ setClient, [ "@wallabag_import.pocket.client" ] ]
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: pocket }

    Wallabag\ImportBundle\Import\WallabagV1Import:
        class: Wallabag\ImportBundle\Import\WallabagV1Import
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\CoreBundle\Helper\ContentProxy'
            - '@Wallabag\CoreBundle\Helper\TagsAssigner'
            - "@event_dispatcher"
            - "%wallabag_core.fetching_error_message_title%"
            - "%wallabag_core.fetching_error_message%"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: wallabag_v1 }

    Wallabag\ImportBundle\Import\WallabagV2Import:
        class: Wallabag\ImportBundle\Import\WallabagV2Import
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\CoreBundle\Helper\ContentProxy'
            - '@Wallabag\CoreBundle\Helper\TagsAssigner'
            - "@event_dispatcher"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: wallabag_v2 }

    Wallabag\ImportBundle\Import\ElcuratorImport:
        class: Wallabag\ImportBundle\Import\ElcuratorImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\CoreBundle\Helper\ContentProxy'
            - '@Wallabag\CoreBundle\Helper\TagsAssigner'
            - "@event_dispatcher"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: elcurator }

    Wallabag\ImportBundle\Import\ReadabilityImport:
        class: Wallabag\ImportBundle\Import\ReadabilityImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\CoreBundle\Helper\ContentProxy'
            - '@Wallabag\CoreBundle\Helper\TagsAssigner'
            - "@event_dispatcher"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: readability }

    Wallabag\ImportBundle\Import\InstapaperImport:
        class: Wallabag\ImportBundle\Import\InstapaperImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\CoreBundle\Helper\ContentProxy'
            - '@Wallabag\CoreBundle\Helper\TagsAssigner'
            - "@event_dispatcher"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: instapaper }

    Wallabag\ImportBundle\Import\PinboardImport:
        class: Wallabag\ImportBundle\Import\PinboardImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\CoreBundle\Helper\ContentProxy'
            - '@Wallabag\CoreBundle\Helper\TagsAssigner'
            - "@event_dispatcher"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: pinboard }

    Wallabag\ImportBundle\Import\DeliciousImport:
        class: Wallabag\ImportBundle\Import\DeliciousImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\CoreBundle\Helper\ContentProxy'
            - '@Wallabag\CoreBundle\Helper\TagsAssigner'
            - "@event_dispatcher"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: delicious }

    Wallabag\ImportBundle\Import\FirefoxImport:
        class: Wallabag\ImportBundle\Import\FirefoxImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\CoreBundle\Helper\ContentProxy'
            - '@Wallabag\CoreBundle\Helper\TagsAssigner'
            - "@event_dispatcher"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: firefox }

    Wallabag\ImportBundle\Import\ChromeImport:
        class: Wallabag\ImportBundle\Import\ChromeImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@Wallabag\CoreBundle\Helper\ContentProxy'
            - '@Wallabag\CoreBundle\Helper\TagsAssigner'
            - "@event_dispatcher"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: chrome }

    Wallabag\ImportBundle\Command\:
        resource: ../../Command/*
        autoconfigure: true
